// LABORATORY TASK
// Create a JavaScript program that stores:
/*• Student name
• Roll number
• Three subject marks
The program should display:
• Student name
• Roll number
• Marks of all three subjects
• Total marks
• Average marks
The program should also contain at least two single-line comments, one multi-line comment, arithmetic operators,
variables, and console.log() statements.*/

let student_name="Deepak choudhary"; // this will store the student name 
let roll_number=04;
let english_marks=85;
let math_marks=90;
let cs_marks=95;

let total_marks=english_marks+math_marks+cs_marks;
let average_marks=total_marks/3;

console.log("student_name:",student_name);
console.log("roll_number:",roll_number);
console.log("english_marks:",english_marks);
console.log("math_marks:",math_marks);
console.log("cs_marks:",cs_marks);
console.log("total_marks:",total_marks);
console.log("average_marks:",average_marks);
